export const START_GOOGLE_SIGN_IN ="START_GOOGLE_SIGN_IN";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAILED = "GOOGLE_SIGN_IN_FAILED";

export const START_FB_SIGNIN = "START_FB_SIGNIN";
export const FB_SIGNIN_SUCCESS = "FB_SIGNIN_SUCCESS";
export const FB_SIGNIN_FAILED = "FB_SIGNIN_FAILED";

export const START_EMAIL_PASSWORD_LOGIN = "START_EMAIL_PASSWORD_LOGIN";
export const EMAIL_PASSWORD_LOGIN_SUCCESS = "EMAIL_PASSWORD_LOGIN_SUCCESS";
export const EMAIL_PASSWORD_LOGIN_FAILED = "EMAIL_PASSWORD_LOGIN_FAILED";

export const START_USER_FETCH_FROM_ASYNC = "START_USER_FETCH_FROM_ASYNC";
export const USER_FETCH_FROM_ASYNC_FAILED = "USER_FETCH_FROM_ASYNC_FAILED";
export const USER_FETCH_FROM_ASYNC_SUCCESS = "USER_FETCH_FROM_ASYNC_SUCCESS";

export const START_SIGN_OUT = "START_SIGN_OUT";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";
