export const START_GOOGLE_SIGN_IN ="START_GOOGLE_SIGN_IN";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const DOCTOR_GOOGLE_SIGN_IN_SUCCESS ="DOCTOR_GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAILED = "GOOGLE_SIGN_IN_FAILED";

export const START_FB_SIGNIN = "START_FB_SIGNIN";
export const FB_SIGNIN_SUCCESS = "FB_SIGNIN_SUCCESS";
export const DOCTOR_FB_SIGNIN_SUCCESS = "DOCTOR_FB_SIGNIN_SUCCESS";
export const FB_SIGNIN_FAILED = "FB_SIGNIN_FAILED";

export const START_EMAIL_PASSWORD_LOGIN = "START_EMAIL_PASSWORD_LOGIN";
export const EMAIL_PASSWORD_LOGIN_SUCCESS = "EMAIL_PASSWORD_LOGIN_SUCCESS";
export const DOCTOR_EMAIL_PASSWORD_LOGIN_SUCCESS = "DOCTOR_EMAIL_PASSWORD_LOGIN_SUCCESS";
export const EMAIL_PASSWORD_LOGIN_FAILED = "EMAIL_PASSWORD_LOGIN_FAILED";

export const START_EMAIL_PASSWORD_SIGNIN = "START_EMAIL_PASSWORD_SIGNIN";
export const EMAIL_PASSWORD_SIGNIN_SUCCESS = "EMAIL_PASSWORD_SIGNIN_SUCCESS";
export const DOCTOR_EMAIL_PASSWORD_SIGNIN_SUCCESS = "DOCTOR_EMAIL_PASSWORD_SIGNIN_SUCCESS";
export const EMAIL_PASSWORD_SIGNIN_FAILED = "EMAIL_PASSWORD_SIGNIN_FAILED";

export const START_USER_FETCH_FROM_ASYNC = "START_USER_FETCH_FROM_ASYNC";
export const USER_FETCH_FROM_ASYNC_FAILED = "USER_FETCH_FROM_ASYNC_FAILED";
export const DOCTOR_USER_FETCH_FROM_ASYNC_SUCCESS = 'DOCTOR_USER_FETCH_FROM_ASYNC_SUCCESS';
export const USER_FETCH_FROM_ASYNC_SUCCESS = "USER_FETCH_FROM_ASYNC_SUCCESS";

export const START_SIGN_OUT = "START_SIGN_OUT";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";

export const PICKER_IMAGE_SOURCE_SUCCESS = "PICKER_IMAGE_SOURCE_SUCCESS";
export const UPLOAD_IMAGE_STARTED = "UPLOAD_IMAGE_STARTED";
export const UPLOAD_IMAGE_FINISHED = "UPLOAD_IMAGE_FINISHED";

export const FIRESTORE_UPLOAD_STARTED = "FIRESTORE_UPLOAD_STARTED";
export const FIRESTORE_UPLOAD_FAILED = "FIRESTORE_UPLOAD_FAILED";
export const FIRESTORE_UPLOAD_SUCCESS = "FIRESTORE_UPLOAD_SUCCESS";

export const DOCTOR_PROFILE_CREATE_START = "DOCTOR_PROFILE_CREATE_START";
export const DOCTOR_PROFILE_CREATE_SUCCESS = "DOCTOR_PROFILE_CREATE_SUCCESS";
export const DOCTOR_PROFILE_CREATE_UPDATE = "DOCTOR_PROFILE_CREATE_UPDATE";
export const DOCTOR_PROFILE_CREATE_FAILED = "DOCTOR_PROFILE_CREATE_FAILED";

export const DOCTOR_AVAILABLE_LIST_FETCH_START = "DOCTOR_AVAILABLE_LIST_FETCH_START";
export const DOCTOR_AVAILABLE_LIST_FETCH_SUCCESS = "DOCTOR_AVAILABLE_LIST_FETCH_SUCCESS";
export const DOCTOR_AVAILABLE_LIST_FETCH_FAILED = "DOCTOR_AVAILABLE_LIST_FETCH_FAILED";

export const AVATAR_FORM_UPLOAD_STARTED = "AVATAR_FORM_UPLOAD_STARTED";
export const AVATAR_FORM_UPLOAD_SUCCESS = "AVATAR_FORM_UPLOAD_SUCCESS";
export const AVATAR_FORM_UPLOAD_FAILED = "AVATAR_FORM_UPLOAD_FAILED";